title: Sleek Learn
author: Okorie John
email: ameachijohn01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a site about my learning program with github
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
theme: minima

# social links
twitter_username: Okjohn01 # DO NOT include the @ character, or else the build will fail!
github_username:  Okoriejohn # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
